---
# - Check if already installed with `grep BUNDLE_VERSION /usr/local/bin/meteor`
- name: Check if Meteor is already installed
  debug:
    msg: "TODO"

- name: Install a new release
  block:
  - name: Create Meteor temp dir
    file:
      path: "{{ meteor_install_tmpdir }}"
      state: directory 
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Fetch Meteor release
    get_url:
      url: "{{ meteor_url }}"
      dest: "{{ meteor_install_tmpdir }}/meteor-{{ meteor_release }}.tar.gz"
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Extract the archive
    unarchive:
      src: "{{ meteor_install_tmpdir }}/meteor-{{ meteor_release }}.tar.gz"
      dest: "{{ meteor_install_tmpdir }}"
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Move extracted files to Meteor home
    copy:
      src: "{{ meteor_install_tmpdir }}/.meteor/"
      dest: "{{ meteor_home }}"
      remote_src: yes
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Remove Meteor temp dir
    file:
      path: "{{ meteor_install_tmpdir }}"
      state: absent

- name: Ensure launch-meteor is symlinked
  file:
    src: "{{ meteor_home }}/scripts/admin/launch-meteor"
    dest: /usr/local/bin/meteor
    state: link
    owner: root
    group: root
