---
- name: Check if Meteor is already installed
  stat:
    path: "{{ meteor_home }}/meteor/meteor"
  register: __meteor_stat

- name: Check currently installed version if needed
  set_fact:
    __meteor_current_version: "{{ __meteor_stat.stat.lnk_target.split('/')[2] }}"
  when: __meteor_stat.stat.exists

- name: Adjust meteor release version if needed
  set_fact:
    __meteor_adjusted_release: "{{ meteor_release }}.0"
  when:
    - __meteor_stat.stat.exists
    - meteor_release.split('.') | count == 2

- name: Save the release number
  set_fact:
    __meteor_adjusted_release: "{{ meteor_release }}"
  when:
    - __meteor_stat.stat.exists
    - meteor_release.split('.') | count == 3

- name: Install a new release
  block:
  - name: Create Meteor temp dir
    file:
      path: "{{ meteor_install_tmpdir }}"
      state: directory 
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Fetch Meteor release
    get_url:
      url: "{{ meteor_url }}"
      dest: "{{ meteor_install_tmpdir }}/meteor-{{ meteor_release }}.tar.gz"
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Extract the archive
    unarchive:
      src: "{{ meteor_install_tmpdir }}/meteor-{{ meteor_release }}.tar.gz"
      dest: "{{ meteor_home }}"
      remote_src: yes
      owner: "{{ meteor_user }}"
      group: "{{ meteor_group }}"

  - name: Unhide the Meteor folder
    command:
      cmd: "mv {{ meteor_home | quote }}/.meteor/ {{ meteor_home | quote }}/meteor"
      creates: "{{ meteor_home }}/meteor"

  - name: Remove Meteor temp dir
    file:
      path: "{{ meteor_install_tmpdir }}"
      state: absent

  when: not __meteor_stat.stat.exists or __meteor_current_version is version(__meteor_adjusted_release, "!=")

- name: Re-stat meteor
  stat:
    path: "{{ meteor_home }}/meteor/meteor"
  register: __meteor_stat

- name: Ensure launch-meteor is symlinked
  file:
    src: "{{ __meteor_stat.stat.lnk_source | dirname }}/scripts/admin/launch-meteor"
    dest: /usr/local/bin/meteor
    state: link
    owner: root
    group: root
